# Generated by Django 5.0.1 on 2024-03-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
    ]
