# Generated by Django 5.0.1 on 2024-03-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_listing_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='bid_counter',
            new_name='bidss',
        ),
        migrations.AlterField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction_listing'),
        ),
    ]
