# Generated by Django 5.0.1 on 2024-03-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_bid_counter_auction_listing_bidss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
