# Generated by Django 5.0.1 on 2024-03-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bids_highest_bid_bids_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
