# Generated by Django 5.0.1 on 2024-03-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_listing_is_closed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='is_closed',
        ),
    ]
