# Generated by Django 5.0.1 on 2024-03-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auction_listing_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
